#our microservice is cilent for eureka
eureka.client.service-url.defaultzone=http://localhost:8761/eureka



# our microservice is clinet for admin
spring.boot.admin.client.url=http://localhost:9999


# To activate actuator end points
management.endpoints.web.exposure.include=*


my.app.name=  Nikhil
